"""
report.py — Markdown report generation for Bug Autopsy.
"""

from __future__ import annotations

import datetime
from typing import Optional

from autopsy.analyzer import DiagnosticResult


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _confidence_badge(score: float) -> str:
    if score >= 0.90:
        return f"🔴 **HIGH** ({score:.0%})"
    if score >= 0.70:
        return f"🟡 **MEDIUM** ({score:.0%})"
    return f"🟢 **LOW** ({score:.0%})"


def _confidence_bar(score: float, width: int = 20) -> str:
    filled = round(score * width)
    return "[" + "█" * filled + "░" * (width - filled) + f"] {score:.0%}"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate(
    results: list[DiagnosticResult],
    source_label: str = "stdin",
    include_toc: bool = True,
) -> str:
    """
    Render a full Markdown autopsy report for the given *results*.

    Parameters
    ----------
    results:
        List of :class:`~autopsy.analyzer.DiagnosticResult` objects.
    source_label:
        Human-readable description of the input source (file path or ``"stdin"``).
    include_toc:
        Whether to prepend a table of contents.
    """
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines: list[str] = []

    # ── Header ──────────────────────────────────────────────────────────────
    lines += [
        "# 🔬 Bug Autopsy Report",
        "",
        f"**Generated:** {now}  ",
        f"**Source:** `{source_label}`  ",
        f"**Errors found:** {len(results)}  ",
        "",
        "---",
        "",
    ]

    if not results:
        lines += [
            "## ✅ No Errors Detected",
            "",
            "Bug Autopsy found no known error patterns in the provided input.",
            "This does not guarantee the code is error-free — consider running additional tests.",
            "",
        ]
        return "\n".join(lines)

    # ── Table of Contents ───────────────────────────────────────────────────
    if include_toc and len(results) > 1:
        lines += ["## Table of Contents", ""]
        for i, r in enumerate(results, 1):
            anchor = f"error-{i}-{r.error_type.lower().replace(' ', '-')}"
            lines.append(f"{i}. [{r.error_type}](#{anchor})")
        lines += ["", "---", ""]

    # ── Summary table ────────────────────────────────────────────────────────
    lines += [
        "## Summary",
        "",
        "| # | Error Type | Confidence | Environment |",
        "|---|-----------|-----------|------------|",
    ]
    for i, r in enumerate(results, 1):
        lines.append(
            f"| {i} | `{r.error_type}` | {_confidence_bar(r.confidence, 10)} | {r.context} |"
        )
    lines += ["", "---", ""]

    # ── Individual error sections ────────────────────────────────────────────
    for i, r in enumerate(results, 1):
        anchor = f"error-{i}-{r.error_type.lower().replace(' ', '-')}"
        lines += [
            f'<a id="{anchor}"></a>',
            f"## Error {i}: `{r.error_type}`",
            "",
            f"> {r.message}",
            "",
            f"**Confidence:** {_confidence_badge(r.confidence)}  ",
            f"**Inferred environment:** {r.context}",
            "",
        ]

        # Explanation
        lines += [
            "### 🧠 Explanation",
            "",
            r.explanation,
            "",
        ]

        # Stack frames
        if r.frames:
            lines += ["### 📍 Stack Trace Locations", ""]
            for frame in r.frames:
                lines.append(
                    f"- **`{frame.function}()`** — `{frame.file}` line {frame.line}"
                )
                if frame.source:
                    lines.append(f"  ```python\n  {frame.source}\n  ```")
            lines.append("")

        # Raw excerpt
        if r.raw_excerpt:
            lines += [
                "### 📋 Raw Excerpt",
                "",
                "```",
                r.raw_excerpt,
                "```",
                "",
            ]

        # Fixes
        lines += ["### 🔧 Recommended Fixes", ""]
        for j, fix in enumerate(r.fixes, 1):
            lines.append(f"{j}. {fix}")
        lines += ["", "---", ""]

    # ── Footer ────────────────────────────────────────────────────────────────
    lines += [
        "_Report generated by [Bug Autopsy](https://github.com/yourname/bug-autopsy) — "
        "turn raw tracebacks into actionable insights._",
        "",
    ]

    return "\n".join(lines)


def save(content: str, path: str) -> None:
    """Write *content* to *path*."""
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    print(f"📄 Report saved → {path}")
